import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  debriefContainer: { flex: 1, backgroundColor: '#000000' },
  debriefHeader: { padding: 20 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { color: '#00FF88', fontSize: 20, fontWeight: 'bold', letterSpacing: 1 },
  meetingTitle: { color: '#FFFFFF', fontSize: 16, marginTop: 10 },
  audioPlayer: { flexDirection: 'row', alignItems: 'center', marginTop: 15, backgroundColor: '#1A1A1A', borderRadius: 8, padding: 12, gap: 10 },
  playButton: { padding: 8 },
  audioInfo: { flex: 1 },
  audioTime: { color: '#FFFFFF', fontSize: 12, fontFamily: 'monospace' },
  audioProgress: { height: 4, backgroundColor: '#333333', borderRadius: 2, marginTop: 6 },
  audioProgressFill: { height: 4, backgroundColor: '#00FF88', borderRadius: 2 },
  debriefContent: { flex: 1, padding: 20 },
  section: { marginBottom: 20 },
  sectionTitle: { color: '#00FF88', fontSize: 14, fontWeight: 'bold', letterSpacing: 1, marginBottom: 10 },
  decisionCard: { backgroundColor: '#1A1A1A', borderRadius: 8, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#333333' },
  decisionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  confidenceIndicator: { width: 8, height: 8, borderRadius: 4 },
  decisionNumber: { color: '#888888', fontSize: 12, fontWeight: 'bold' },
  confidenceText: { color: '#00FF88', fontSize: 12, fontWeight: 'bold', marginLeft: 'auto' },
  decisionText: { color: '#FFFFFF', fontSize: 14, lineHeight: 20 },
  decisionMeta: { flexDirection: 'row', marginTop: 10, gap: 15 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaText: { color: '#888888', fontSize: 12 },
  followUpCard: { backgroundColor: '#1A1A1A', borderRadius: 8, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#333333' },
  followUpHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  followUpType: { color: '#888888', fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },
  confidenceBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 12 },
  confidenceBadgeText: { color: '#000000', fontSize: 11, fontWeight: 'bold' },
  followUpContent: { color: '#FFFFFF', fontSize: 14, lineHeight: 20 },
  recipientRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 8 },
  recipientText: { color: '#888888', fontSize: 12 },
  transcriptContainer: { backgroundColor: '#1A1A1A', borderRadius: 8, padding: 12 },
  transcriptText: { color: '#CCCCCC', fontSize: 13, lineHeight: 20, fontFamily: 'monospace' },
  debriefFooter: { flexDirection: 'row', padding: 20, gap: 10 },
  footerButton: { flex: 1, backgroundColor: '#00FF88', paddingVertical: 14, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  footerButtonSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#333333' },
  footerButtonText: { color: '#000000', fontSize: 16, fontWeight: 'bold' },
  footerButtonTextSecondary: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
});
