import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  briefingContainer: { flex: 1, backgroundColor: '#000000' },
  briefingHeader: { padding: 20 },
  briefingTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  briefingTitle: { color: '#00FF88', fontSize: 20, fontWeight: 'bold', letterSpacing: 1 },
  countdownContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 15, gap: 10 },
  playButton: { padding: 10 },
  countdownText: { color: '#FFFFFF', fontSize: 16, fontFamily: 'monospace' },
  progressBar: { flex: 1, height: 4, backgroundColor: '#333333', borderRadius: 2 },
  progressFill: { height: 4, backgroundColor: '#00FF88', borderRadius: 2 },
  briefingContent: { flex: 1, padding: 20 },
  summarySection: { marginBottom: 20 },
  sectionTitle: { color: '#00FF88', fontSize: 14, fontWeight: 'bold', letterSpacing: 1, marginBottom: 10 },
  summaryText: { color: '#CCCCCC', fontSize: 14, lineHeight: 22 },
  section: { marginBottom: 20 },
  prioritiesContainer: { gap: 10 },
  priorityBadge: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 8, gap: 10 },
  priorityText: { color: '#000000', fontSize: 14, fontWeight: 'bold', flex: 1 },
  priorityConfidence: { color: '#000000', fontSize: 12, fontWeight: 'bold' },
  timeSlot: { padding: 12, backgroundColor: '#1A1A1A', borderRadius: 8, marginBottom: 8 },
  timeText: { color: '#00FFFF', fontSize: 14, fontWeight: 'bold' },
  timePurpose: { color: '#CCCCCC', fontSize: 12, marginTop: 4 },
  actionItem: { backgroundColor: '#1A1A1A', padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#333333' },
  actionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  actionText: { color: '#FFFFFF', fontSize: 14, flex: 1 },
  confidenceBadge: { backgroundColor: '#333333', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  confidenceBadgeText: { color: '#00FF88', fontSize: 12, fontWeight: 'bold' },
  effortIndicator: { marginTop: 8 },
  effortText: { color: '#888888', fontSize: 12 },
  delegationItem: { backgroundColor: '#1A1A1A', padding: 12, borderRadius: 8, marginBottom: 8, flexDirection: 'row', alignItems: 'center' },
  delegationContent: { flex: 1 },
  delegationTask: { color: '#FFFFFF', fontSize: 14 },
  delegationTo: { color: '#888888', fontSize: 12, marginTop: 4 },
  delegationConfidence: { marginLeft: 10 },
  briefingFooter: { flexDirection: 'row', padding: 20, gap: 10 },
  briefingButton: { flex: 1, backgroundColor: '#00FF88', paddingVertical: 14, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  briefingButtonSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#333333' },
  briefingButtonText: { color: '#000000', fontSize: 16, fontWeight: 'bold' },
  briefingButtonTextSecondary: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
});
